name: env name
on: push
jobs:
  build:
   runs-on: ubuntu-latest
   env: 
     my_name: "hruthik"
   steps:
     - name: environr mvariable
       run: |
        echo "hii this is ${{vars.my_name}}"
        echo "hii how are you ${{vars.my_name}}"
       
