name: variable-demo
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check condition
        if: github.actor == 'hruhtikprabhu' || github.actor == 'shashnak'
        run: echo "${{ github.actor }} has pushed"
