name: demo-practise
on: workflow_dispatch
jobs:
 devops:
  runs-on: ubuntu-latest
  steps:
    - name: deifing the jobs
      run: echo "this is devops job"
 test:
   runs-on: ubuntu-latest
   needs: devops
   steps:
     - name: defing the jobs of test
       run:  echo "this shld run after the devops"
 prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: prod dep shld checkouth the code 
        uses: actions/checkout@v4
        
